### ISSUE TITLE
no support for Virtualbox 5.x?

### ISSUE THREAD

**Issue by kenyee** [smxi/svmi#1]
Current latest 4.3.28 virtualbox has issues w/ Kernel 4.3:

Uninstalling modules from DKMS
  removing old DKMS module vboxhost version  4.3.28

------------------------------
Deleting module version: 4.3.28
completely from the DKMS tree.
------------------------------
Done.
Attempting to install using DKMS

Creating symlink /var/lib/dkms/vboxhost/4.3.28/source ->
                 /usr/src/vboxhost-4.3.28

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.3.0-0.slh.2-aptosid-amd64 -C /lib/modules/4.3.0-0.slh.2-aptosid-amd64/build M=/var/lib/dkms/vboxhost/4.3.28/build....(bad exit status: 2)
Failed to install using DKMS, attempting to install without
make KBUILD_VERBOSE=1 SUBDIRS=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 CONFIG_MODULE_SIG= -C /lib/modules/4.3.0-0.slh.2-aptosid-amd64/build modules
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)
mkdir -p /tmp/vbox.0/.tmp_versions ; rm -f /tmp/vbox.0/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/tmp

**Comment by smxi** [comment]
:First of all, I don't care about DKMS, that's not my problem, so that's something you fix yourself.

Second of all, the current version of svmi had 5.06, as you can see from this commit:

https://github.com/smxi/svmi/commit/1d14343a7b14d8c482af2977574d1c4991ddebfb

So I have no idea what you are talking about. There is only one version of svmi, or anything else I do, and that's the current version. 

So if you aren't running the current version, and I have no idea how you would have managed that, since svmi, sgfxi, smxi, all update themselves automatically, then I don't support your actions at all.

Since the current svmi uses vbox 5.x, your issue is invalid, and I'm closing it.

**Comment by kenyee** [comment]
Thanks...sorry about that.  No idea why it did that either.  I did run smxi and it updated everything but it still claimed the latest virtual box was 4.3.28.  Apologies for not looking at the code to confirm first :-(

**Comment by smxi** [comment]
Oh, no, I'm sorry in that case. I think what must have happened was that I simply forgot to upload the current svmi, in that case, all the negatives in my response have to be redirected to me. I had to switch from google code to github, and in the process, some of the things I was used to doing I still haven't adjusted to the new formats, so I will assume an error on my part.

Again,, apologies for my response in that case, if you ran smxi, then there is no possible explanation for the error than my having uploaded the wrong svmi originally.
